@"

CREATE TABLE IF NOT EXISTS `STRAVA_TOKENS` (
	`ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`ATHLETE_ID` BIGINT(20) NOT NULL,
	`ACCESS_TOKEN` VARCHAR(2048) NOT NULL COLLATE 'utf8mb4_general_ci',
	`REFRESH_TOKEN` VARCHAR(2048) NOT NULL COLLATE 'utf8mb4_general_ci',
	`EXPIRES_AT` DATETIME(3) NULL DEFAULT NULL,
	`TOKEN_TYPE` VARCHAR(64) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`SCOPE` VARCHAR(512) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`CREATED_AT` DATETIME(3) NOT NULL DEFAULT current_timestamp(3),
	`UPDATED_AT` DATETIME(3) NOT NULL DEFAULT current_timestamp(3) ON UPDATE current_timestamp(3),
	`REVOKED` TINYINT(1) NOT NULL DEFAULT '0',
	`RAW_RESPONSE` TEXT NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	PRIMARY KEY (`ID`) USING BTREE,
	UNIQUE INDEX `ux_strava_athlete` (`ATHLETE_ID`) USING BTREE,
	INDEX `idx_expires_at` (`EXPIRES_AT`) USING BTREE
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=6
;


CREATE TABLE IF NOT EXISTS STRAVA_ACTIVITY
(
    ID BIGINT NOT NULL,

    EXTERNAL_ID VARCHAR(255),
    UPLOAD_ID BIGINT,
    ATHLETE_ID BIGINT,

    NAME VARCHAR(255),
    DESCRIPTION TEXT,

    DISTANCE DOUBLE,
    MOVING_TIME INT,
    ELAPSED_TIME INT,

    TOTAL_ELEVATION_GAIN DOUBLE,
    ELEV_HIGH DOUBLE,
    ELEV_LOW DOUBLE,

    TYPE VARCHAR(50),
    SPORT_TYPE VARCHAR(100),
    WORKOUT_TYPE INT,

    START_DATE DATETIME,
    START_DATE_LOCAL DATETIME,

    TIMEZONE VARCHAR(100),
    UTC_OFFSET INT,

    LOCATION_CITY VARCHAR(100),
    LOCATION_STATE VARCHAR(100),
    LOCATION_COUNTRY VARCHAR(100),

    START_LATITUDE DOUBLE,
    START_LONGITUDE DOUBLE,

    END_LATITUDE DOUBLE,
    END_LONGITUDE DOUBLE,

    AVERAGE_SPEED DOUBLE,
    MAX_SPEED DOUBLE,

    AVERAGE_WATTS DOUBLE,
    MAX_WATTS DOUBLE,
    WEIGHTED_AVERAGE_WATTS DOUBLE,
    DEVICEWATTS BOOLEAN,

    AVERAGE_HEARTRATE DOUBLE,
    MAX_HEARTRATE DOUBLE,

    AVERAGE_TEMP DOUBLE,
    AVERAGE_CADENCE DOUBLE,

    CALORIES DOUBLE,
    SUFFER_SCORE INT,

    ACHIEVEMENT_COUNT INT,
    KUDOS_COUNT INT,
    COMMENT_COUNT INT,
    ATHLETE_COUNT INT,
    PHOTO_COUNT INT,

    GEAR_ID VARCHAR(50),
    GEAR_NAME VARCHAR(255),

    TRAINER BOOLEAN,
    COMMUTE BOOLEAN,
    MANUAL BOOLEAN,
    PRIVATE_FLAG BOOLEAN,
    FLAGGED BOOLEAN,

    VISIBILITY VARCHAR(50),
    DEVICE_NAME VARCHAR(255),
    EMBED_TOKEN VARCHAR(255),

    RESOURCE_STATE INT,

    SPLIT_COUNT INT,
    LAP_COUNT INT,
    SEGMENT_EFFORT_COUNT INT,

    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
               ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (ID),

    INDEX IDX_STRAVA_ACTIVITY_ATHLETE_ID (ATHLETE_ID),
    INDEX IDX_STRAVA_ACTIVITY_START_DATE (START_DATE),
    INDEX IDX_STRAVA_ACTIVITY_SPORT_TYPE (SPORT_TYPE),
    INDEX IDX_STRAVA_ACTIVITY_GEAR_ID (GEAR_ID)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS STRAVA_TRACKPOINT
(
    ACTIVITY_ID BIGINT NOT NULL,
    TIME INT,
    DISTANCE FLOAT,
    LATITUDE DOUBLE,
    LONGITUDE DOUBLE,
    ALTITUDE FLOAT,
    HEARTRATE INT,
    WATTS INT,
    SPEED FLOAT,
    TEMPERATURE INT,
    CADENCE INT,
    GRADE FLOAT NULL DEFAULT NULL,
    PRIMARY KEY (ACTIVITY_ID, TIME),
    INDEX IDX_TRACKPOINT_ACTIVITY (ACTIVITY_ID)
);


-- Exportiere Struktur von Tabelle swstest.STRAVA_BIKE
CREATE TABLE IF NOT EXISTS `STRAVA_BIKE` (
  `GEAR_ID` varchar(50) NOT NULL,
  `GEAR_NAME` varchar(255) DEFAULT NULL,
  `CRR` float DEFAULT NULL,
  `CDA` float DEFAULT NULL,
  `TYP` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `GEWICHT` float DEFAULT NULL,
  PRIMARY KEY (`GEAR_ID`),
  KEY `IDX_STRAVA_BIKE_GEAR_NAME` (`GEAR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Exportiere Daten aus Tabelle swstest.STRAVA_BIKE: ~11 rows (ungefähr)
INSERT INTO `STRAVA_BIKE` (`GEAR_ID`, `GEAR_NAME`, `CRR`, `CDA`, `TYP`, `GEWICHT`) VALUES
	('b10395535', 'Wahoo Kickr Core', NULL, NULL, 'E', NULL),
	('b13106325', 'BMC', 0.005, 0.3, 'R', 7.5),
	('b14388263', 'Specialized Epic', 0.012, 0.45, 'M', 11.8),
	('b3209245', 'Cannondale Synapse', 0.005, 0.32, 'R', 8.2),
	('b3209247', 'Scalpel 3 26"', 0.01, 0.4, 'M', 11),
	('b3705431', 'MTB Scalpel 3  29"', 0.009, 0.4, 'M', 11.7),
	('b3823455', 'Daum 8i', NULL, NULL, 'E', NULL),
	('b5199429', 'KTM eBike Mutti', 0.012, 0.45, 'M', 24),
	('b5222017', 'Cannondale R600', 0.005, 0.32, 'R', 9),
	('b5222174', 'XXX Rad', NULL, NULL, 'M', 14),
	('b6801898', 'RR Cannondale Synapse Disc', 0.005, 0.32, 'R', 8.2);









"@ | Set-Content temp.sql

cat .\temp.sql | docker exec -i mysql8 mysql -u root -praptor swstest

del temp.sql

docker exec -it mysql8 mysql -u root -praptor swstest -e "SHOW TABLES;"