# SpringDoc / Swagger UI configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
# Anzeige der Request-Dauer in Swagger UI
springdoc.swagger-ui.display-request-duration=true
server.port=8099
#
logging.level.root=INFO
logging.file.name=D:/LOG/SportWebServer.log
# Konfigurationswert fuer SchedulerService
testvar=Hallo_XXX