# SpringDoc / Swagger UI configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
# Anzeige der Request-Dauer in Swagger UI
springdoc.swagger-ui.display-request-duration=true
server.port=8099
#
# MySQL Database Configuration
#spring.datasource.url=jdbc:mysql://10.0.0.88:3306/sport
#spring.datasource.username=sport
#spring.datasource.password=Raptor00
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/testdb
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
# Oracle Datenbank
#spring.datasource.url=jdbc:oracle:thin:@2236asf4bde:1521:bd5974r2
#spring.datasource.username=hbdesim
#spring.datasource.password=simsim
#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
#
# SQLite Datenbank
#spring.datasource.url=jdbc:sqlite:C:/Users/zollesh/AppData/Roaming/MySport/MySport.db
#spring.datasource.driver-class-name=org.sqlite.JDBC
#
logging.level.root=INFO
logging.file.name=D:/LOG/SportWebServer.log
# Konfigurationswert fuer SchedulerService
testvar=3283
#
#
# STRAVA
strava.client.id=51743
strava.client.secret=16495e62687cf8699a382fa91f3183e88f7ba5a0
strava.redirect.uri=http://localhost:8099/strava/callback